# fanuc_cage_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
fanuc_cage_arm:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
    a1:  0.075
    a2: -0.215
    b:   -0.005
    c1:  0.425
    c2:  0.84
    c3:  0.88986
    c4:  0.1878
  opw_kinematics_joint_offsets: [0, 0, -1.57079632679, 0, 0, -1.57079632679]
  opw_kinematics_joint_sign_corrections: [1, 1, -1, -1, -1, -1]