# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fanuc_cage_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - fanuc_joint_1
    - fanuc_joint_2
    - fanuc_joint_3
    - fanuc_joint_4
    - fanuc_joint_5
    - fanuc_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
fanuc_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - fanuc_joint_1
    - fanuc_joint_2
    - fanuc_joint_3
    - fanuc_joint_4
    - fanuc_joint_5
    - fanuc_joint_6
  gains:
    fanuc_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1