fanuc_cage_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - fanuc_joint_1
    - fanuc_joint_2
    - fanuc_joint_3
    - fanuc_joint_4
    - fanuc_joint_5
    - fanuc_joint_6
  gains:
    fanuc_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fanuc_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1