<?xml version="1.0"?>
<robot name="hopper_long" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find hopper_long)/urdf/hopper_long_macro.xacro"/>
  <xacro:hopper_long prefix=""/>

  <xacro:property name="h_offset" value="0.1" />
  <xacro:property name="h_hopper" value="2.286" /> <!-- 82 inch = 2.0828 m, 90 inch = 2.286 m -->
  <xacro:property name="r_hopper" value="0.25" /> 
  <xacro:property name="theta" value="${-45.0/180.0*pi}" /> <!-- rotation around z axis angle (rad)  -->

  <!-- Pouring point xyz -->
  <xacro:property name="x_pouring_point" value="${r_hopper * cos(theta)}" /> 
  <xacro:property name="y_pouring_point" value="${r_hopper * sin(theta)}" /> 
  <xacro:property name="z_pouring_point" value="${h_hopper + h_offset}" /> 

  <!-- Pouring point RPY -->
  <xacro:property name="R_pouring_point" value="${90.0/180.0*pi}" /> 
  <xacro:property name="P_pouring_point" value="${0.0/180.0*pi}" /> 
  <xacro:property name="Y_pouring_point" value="${theta}" /> 


  <link name="hopper_long_base_plate">
    <!-- <visual>
      <origin rpy="0 0 0" xyz="0 0 0.0127"/>
      <geometry>        
        <box size="0.9144 0.9144 0.0254"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.0127"/>
      <geometry>        
        <box size="0.9144 0.9144 0.0254"/>
      </geometry>     
    </collision> -->
  </link>

  <link name="hopper_long_pouring_point">
  </link>

  <joint name="hopper_long_base_plate" type="fixed">
    <parent link="hopper_long_base_plate"/>
    <child link="hopper_long_base_link"/>
    <!-- <origin rpy="0 0 0" xyz="0 0 .0254"/> -->
    <!-- <origin rpy="1.5708 0 1.5708" xyz="0 0 0"/> -->
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="hopper_long_pouring_point" type="fixed">
    <parent link="hopper_long_base_link"/>
    <child link="hopper_long_pouring_point"/>
    <origin xyz="${x_pouring_point} ${y_pouring_point} ${z_pouring_point}" rpy="${R_pouring_point} ${P_pouring_point} ${Y_pouring_point}"/>
  </joint>

</robot>
